version: '3'
networks:
 udrepository:

services:
   ud-repository-users-ms:
     build: .
     container_name: ud-repository-users-ms
     restart: on-failure
     env_file:
        - .env
     networks:
        - udrepository          

networks:
  udrepository:
    external: true
