version: '3'
networks:
 campus_virtual:

services:
   ud-repository-users-ms:
     image: planesticud/ud-repository-users-ms
     container_name: ud-repository-users-ms
     restart: on-failure
     env_file:
        - .env
     networks:
        - campus_virtual          

networks:
  campus_virtual:
    external: true
